// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	model "github.com/nedrocks/delphisbe/graph/model"
	mock "github.com/stretchr/testify/mock"
)

// AutoPostDiscussionIter is an autogenerated mock type for the AutoPostDiscussionIter type
type AutoPostDiscussionIter struct {
	mock.Mock
}

// Close provides a mock function with given fields:
func (_m *AutoPostDiscussionIter) Close() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Next provides a mock function with given fields: discussion
func (_m *AutoPostDiscussionIter) Next(discussion *model.DiscussionAutoPost) bool {
	ret := _m.Called(discussion)

	var r0 bool
	if rf, ok := ret.Get(0).(func(*model.DiscussionAutoPost) bool); ok {
		r0 = rf(discussion)
	} else {
		r0 = ret.Get(0).(bool)
	}

	return r0
}
