// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	twitter "github.com/dghubble/go-twitter/twitter"
	mock "github.com/stretchr/testify/mock"
)

// TwitterClient is an autogenerated mock type for the TwitterClient type
type TwitterClient struct {
	mock.Mock
}

// FriendshipLookup provides a mock function with given fields: fromScreenName, toScreenName
func (_m *TwitterClient) FriendshipLookup(fromScreenName string, toScreenName string) (*twitter.Relationship, error) {
	ret := _m.Called(fromScreenName, toScreenName)

	var r0 *twitter.Relationship
	if rf, ok := ret.Get(0).(func(string, string) *twitter.Relationship); ok {
		r0 = rf(fromScreenName, toScreenName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*twitter.Relationship)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(fromScreenName, toScreenName)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LookupUsers provides a mock function with given fields: screenNames
func (_m *TwitterClient) LookupUsers(screenNames []string) ([]twitter.User, error) {
	ret := _m.Called(screenNames)

	var r0 []twitter.User
	if rf, ok := ret.Get(0).(func([]string) []twitter.User); ok {
		r0 = rf(screenNames)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]twitter.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(screenNames)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SearchUsers provides a mock function with given fields: query, page, count
func (_m *TwitterClient) SearchUsers(query string, page int, count int) ([]twitter.User, error) {
	ret := _m.Called(query, page, count)

	var r0 []twitter.User
	if rf, ok := ret.Get(0).(func(string, int, int) []twitter.User); ok {
		r0 = rf(query, page, count)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]twitter.User)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(query, page, count)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
