// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"fmt"
	"io"
	"strconv"
	"time"
)

type DiscussionNotificationPreferences interface {
	IsDiscussionNotificationPreferences()
}

type DiscussionSubscriptionEntity interface {
	IsDiscussionSubscriptionEntity()
}

type Entity interface {
	IsEntity()
}

type AddDiscussionParticipantInput struct {
	GradientColor *GradientColor `json:"gradientColor"`
	FlairID       *string        `json:"flairID"`
	HasJoined     *bool          `json:"hasJoined"`
	IsAnonymous   bool           `json:"isAnonymous"`
}

type CanJoinDiscussionResponse struct {
	Response   DiscussionJoinabilityResponse `json:"response"`
	Reason     *string                       `json:"reason"`
	ReasonCode *int                          `json:"reasonCode"`
}

type ConciergeContent struct {
	AppActionID *string            `json:"appActionID"`
	MutationID  *string            `json:"mutationID"`
	Options     []*ConciergeOption `json:"options"`
}

type ConciergeOption struct {
	Text     string `json:"text"`
	Value    string `json:"value"`
	Selected bool   `json:"selected"`
}

type DiscussionCreationSettings struct {
	DiscussionJoinability DiscussionJoinabilitySetting `json:"discussionJoinability"`
}

type DiscussionInput struct {
	AnonymityType         *AnonymityType                `json:"anonymityType"`
	Title                 *string                       `json:"title"`
	Description           *string                       `json:"description"`
	AutoPost              *bool                         `json:"autoPost"`
	IdleMinutes           *int                          `json:"idleMinutes"`
	PublicAccess          *bool                         `json:"publicAccess"`
	IconURL               *string                       `json:"iconURL"`
	DiscussionJoinability *DiscussionJoinabilitySetting `json:"discussionJoinability"`
}

type DiscussionLinkAccess struct {
	DiscussionID     string `json:"discussionID"`
	InviteLinkURL    string `json:"inviteLinkURL"`
	VipInviteLinkURL string `json:"vipInviteLinkURL"`
	CreatedAt        string `json:"createdAt"`
	UpdatedAt        string `json:"updatedAt"`
	IsDeleted        bool   `json:"isDeleted"`
}

type DiscussionSubscriptionEvent struct {
	EventType DiscussionSubscriptionEventType `json:"eventType"`
	Entity    DiscussionSubscriptionEntity    `json:"entity"`
}

type Media struct {
	ID                string             `json:"id"`
	CreatedAt         string             `json:"createdAt"`
	IsDeleted         bool               `json:"isDeleted"`
	DeletedReasonCode *PostDeletedReason `json:"deletedReasonCode"`
	MediaType         *string            `json:"mediaType"`
	MediaSize         *MediaSize         `json:"mediaSize"`
	AssetLocation     *string            `json:"assetLocation"`
}

type MediaSize struct {
	Height int     `json:"height"`
	Width  int     `json:"width"`
	SizeKb float64 `json:"sizeKb"`
}

type ParticipantNotificationPreferences struct {
	ID string `json:"id"`
}

func (ParticipantNotificationPreferences) IsDiscussionNotificationPreferences() {}

type ParticipantProfile struct {
	IsAnonymous   *bool          `json:"isAnonymous"`
	Flair         *Flair         `json:"flair"`
	GradientColor *GradientColor `json:"gradientColor"`
}

type PollInput struct {
	PollText string    `json:"pollText"`
	EndTime  time.Time `json:"endTime"`
	Option1  string    `json:"option1"`
	Option2  string    `json:"option2"`
	Option3  *string   `json:"option3"`
	Option4  *string   `json:"option4"`
}

type PostContentInput struct {
	PostText          string     `json:"postText"`
	PostType          PostType   `json:"postType"`
	MentionedEntities []string   `json:"mentionedEntities"`
	QuotedPostID      *string    `json:"quotedPostID"`
	MediaID           *string    `json:"mediaID"`
	Poll              *PollInput `json:"poll"`
	ImportedContentID *string    `json:"importedContentID"`
	Preview           *string    `json:"preview"`
}

type TwitterUserInfo struct {
	ID              string `json:"id"`
	Name            string `json:"name"`
	DisplayName     string `json:"displayName"`
	ProfileImageURL string `json:"profileImageURL"`
	Verified        bool   `json:"verified"`
	Invited         bool   `json:"invited"`
}

type TwitterUserInput struct {
	Name string `json:"name"`
}

type URL struct {
	DisplayText string `json:"displayText"`
	URL         string `json:"url"`
}

type UnknownEntity struct {
	ID string `json:"id"`
}

func (UnknownEntity) IsEntity() {}

type UpdateParticipantInput struct {
	GradientColor   *GradientColor `json:"gradientColor"`
	IsUnsetGradient *bool          `json:"isUnsetGradient"`
	FlairID         *string        `json:"flairID"`
	IsUnsetFlairID  *bool          `json:"isUnsetFlairID"`
	IsAnonymous     *bool          `json:"isAnonymous"`
	HasJoined       *bool          `json:"hasJoined"`
}

type ViewerNotificationPreferences struct {
	ID string `json:"id"`
}

func (ViewerNotificationPreferences) IsDiscussionNotificationPreferences() {}

type AnonymityType string

const (
	AnonymityTypeUnknown AnonymityType = "UNKNOWN"
	AnonymityTypeWeak    AnonymityType = "WEAK"
	AnonymityTypeStrong  AnonymityType = "STRONG"
)

var AllAnonymityType = []AnonymityType{
	AnonymityTypeUnknown,
	AnonymityTypeWeak,
	AnonymityTypeStrong,
}

func (e AnonymityType) IsValid() bool {
	switch e {
	case AnonymityTypeUnknown, AnonymityTypeWeak, AnonymityTypeStrong:
		return true
	}
	return false
}

func (e AnonymityType) String() string {
	return string(e)
}

func (e *AnonymityType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AnonymityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AnonymityType", str)
	}
	return nil
}

func (e AnonymityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DiscussionJoinabilityResponse string

const (
	DiscussionJoinabilityResponseAlreadyJoined     DiscussionJoinabilityResponse = "ALREADY_JOINED"
	DiscussionJoinabilityResponseApprovedNotJoined DiscussionJoinabilityResponse = "APPROVED_NOT_JOINED"
	DiscussionJoinabilityResponseAwaitingApproval  DiscussionJoinabilityResponse = "AWAITING_APPROVAL"
	DiscussionJoinabilityResponseApprovalRequired  DiscussionJoinabilityResponse = "APPROVAL_REQUIRED"
	DiscussionJoinabilityResponseDenied            DiscussionJoinabilityResponse = "DENIED"
)

var AllDiscussionJoinabilityResponse = []DiscussionJoinabilityResponse{
	DiscussionJoinabilityResponseAlreadyJoined,
	DiscussionJoinabilityResponseApprovedNotJoined,
	DiscussionJoinabilityResponseAwaitingApproval,
	DiscussionJoinabilityResponseApprovalRequired,
	DiscussionJoinabilityResponseDenied,
}

func (e DiscussionJoinabilityResponse) IsValid() bool {
	switch e {
	case DiscussionJoinabilityResponseAlreadyJoined, DiscussionJoinabilityResponseApprovedNotJoined, DiscussionJoinabilityResponseAwaitingApproval, DiscussionJoinabilityResponseApprovalRequired, DiscussionJoinabilityResponseDenied:
		return true
	}
	return false
}

func (e DiscussionJoinabilityResponse) String() string {
	return string(e)
}

func (e *DiscussionJoinabilityResponse) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiscussionJoinabilityResponse(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiscussionJoinabilityResponse", str)
	}
	return nil
}

func (e DiscussionJoinabilityResponse) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DiscussionJoinabilitySetting string

const (
	DiscussionJoinabilitySettingAllowTwitterFriends DiscussionJoinabilitySetting = "ALLOW_TWITTER_FRIENDS"
	DiscussionJoinabilitySettingAllRequireApproval  DiscussionJoinabilitySetting = "ALL_REQUIRE_APPROVAL"
)

var AllDiscussionJoinabilitySetting = []DiscussionJoinabilitySetting{
	DiscussionJoinabilitySettingAllowTwitterFriends,
	DiscussionJoinabilitySettingAllRequireApproval,
}

func (e DiscussionJoinabilitySetting) IsValid() bool {
	switch e {
	case DiscussionJoinabilitySettingAllowTwitterFriends, DiscussionJoinabilitySettingAllRequireApproval:
		return true
	}
	return false
}

func (e DiscussionJoinabilitySetting) String() string {
	return string(e)
}

func (e *DiscussionJoinabilitySetting) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiscussionJoinabilitySetting(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiscussionJoinabilitySetting", str)
	}
	return nil
}

func (e DiscussionJoinabilitySetting) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type DiscussionSubscriptionEventType string

const (
	DiscussionSubscriptionEventTypePostAdded         DiscussionSubscriptionEventType = "POST_ADDED"
	DiscussionSubscriptionEventTypePostDeleted       DiscussionSubscriptionEventType = "POST_DELETED"
	DiscussionSubscriptionEventTypeParticipantBanned DiscussionSubscriptionEventType = "PARTICIPANT_BANNED"
)

var AllDiscussionSubscriptionEventType = []DiscussionSubscriptionEventType{
	DiscussionSubscriptionEventTypePostAdded,
	DiscussionSubscriptionEventTypePostDeleted,
	DiscussionSubscriptionEventTypeParticipantBanned,
}

func (e DiscussionSubscriptionEventType) IsValid() bool {
	switch e {
	case DiscussionSubscriptionEventTypePostAdded, DiscussionSubscriptionEventTypePostDeleted, DiscussionSubscriptionEventTypeParticipantBanned:
		return true
	}
	return false
}

func (e DiscussionSubscriptionEventType) String() string {
	return string(e)
}

func (e *DiscussionSubscriptionEventType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DiscussionSubscriptionEventType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DiscussionSubscriptionEventType", str)
	}
	return nil
}

func (e DiscussionSubscriptionEventType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type GradientColor string

const (
	GradientColorUnknown    GradientColor = "UNKNOWN"
	GradientColorMauve      GradientColor = "MAUVE"
	GradientColorFuschia    GradientColor = "FUSCHIA"
	GradientColorCinnabar   GradientColor = "CINNABAR"
	GradientColorVermillion GradientColor = "VERMILLION"
	GradientColorCerulean   GradientColor = "CERULEAN"
	GradientColorTurquoise  GradientColor = "TURQUOISE"
	GradientColorCeladon    GradientColor = "CELADON"
	GradientColorTaupe      GradientColor = "TAUPE"
	GradientColorSaffron    GradientColor = "SAFFRON"
	GradientColorViridian   GradientColor = "VIRIDIAN"
	GradientColorChartruese GradientColor = "CHARTRUESE"
	GradientColorLavender   GradientColor = "LAVENDER"
	GradientColorGoldenrod  GradientColor = "GOLDENROD"
	GradientColorSeafoam    GradientColor = "SEAFOAM"
	GradientColorAzalea     GradientColor = "AZALEA"
	GradientColorViolet     GradientColor = "VIOLET"
	GradientColorMahogany   GradientColor = "MAHOGANY"
)

var AllGradientColor = []GradientColor{
	GradientColorUnknown,
	GradientColorMauve,
	GradientColorFuschia,
	GradientColorCinnabar,
	GradientColorVermillion,
	GradientColorCerulean,
	GradientColorTurquoise,
	GradientColorCeladon,
	GradientColorTaupe,
	GradientColorSaffron,
	GradientColorViridian,
	GradientColorChartruese,
	GradientColorLavender,
	GradientColorGoldenrod,
	GradientColorSeafoam,
	GradientColorAzalea,
	GradientColorViolet,
	GradientColorMahogany,
}

func (e GradientColor) IsValid() bool {
	switch e {
	case GradientColorUnknown, GradientColorMauve, GradientColorFuschia, GradientColorCinnabar, GradientColorVermillion, GradientColorCerulean, GradientColorTurquoise, GradientColorCeladon, GradientColorTaupe, GradientColorSaffron, GradientColorViridian, GradientColorChartruese, GradientColorLavender, GradientColorGoldenrod, GradientColorSeafoam, GradientColorAzalea, GradientColorViolet, GradientColorMahogany:
		return true
	}
	return false
}

func (e GradientColor) String() string {
	return string(e)
}

func (e *GradientColor) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = GradientColor(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid GradientColor", str)
	}
	return nil
}

func (e GradientColor) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type InviteRequestStatus string

const (
	InviteRequestStatusAccepted  InviteRequestStatus = "ACCEPTED"
	InviteRequestStatusRejected  InviteRequestStatus = "REJECTED"
	InviteRequestStatusPending   InviteRequestStatus = "PENDING"
	InviteRequestStatusCancelled InviteRequestStatus = "CANCELLED"
)

var AllInviteRequestStatus = []InviteRequestStatus{
	InviteRequestStatusAccepted,
	InviteRequestStatusRejected,
	InviteRequestStatusPending,
	InviteRequestStatusCancelled,
}

func (e InviteRequestStatus) IsValid() bool {
	switch e {
	case InviteRequestStatusAccepted, InviteRequestStatusRejected, InviteRequestStatusPending, InviteRequestStatusCancelled:
		return true
	}
	return false
}

func (e InviteRequestStatus) String() string {
	return string(e)
}

func (e *InviteRequestStatus) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = InviteRequestStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid InviteRequestStatus", str)
	}
	return nil
}

func (e InviteRequestStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type Platform string

const (
	PlatformUnknown Platform = "UNKNOWN"
	PlatformIos     Platform = "IOS"
	PlatformAndroid Platform = "ANDROID"
	PlatformWeb     Platform = "WEB"
)

var AllPlatform = []Platform{
	PlatformUnknown,
	PlatformIos,
	PlatformAndroid,
	PlatformWeb,
}

func (e Platform) IsValid() bool {
	switch e {
	case PlatformUnknown, PlatformIos, PlatformAndroid, PlatformWeb:
		return true
	}
	return false
}

func (e Platform) String() string {
	return string(e)
}

func (e *Platform) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Platform(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Platform", str)
	}
	return nil
}

func (e Platform) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PostDeletedReason string

const (
	PostDeletedReasonUnknown            PostDeletedReason = "UNKNOWN"
	PostDeletedReasonModeratorRemoved   PostDeletedReason = "MODERATOR_REMOVED"
	PostDeletedReasonParticipantRemoved PostDeletedReason = "PARTICIPANT_REMOVED"
)

var AllPostDeletedReason = []PostDeletedReason{
	PostDeletedReasonUnknown,
	PostDeletedReasonModeratorRemoved,
	PostDeletedReasonParticipantRemoved,
}

func (e PostDeletedReason) IsValid() bool {
	switch e {
	case PostDeletedReasonUnknown, PostDeletedReasonModeratorRemoved, PostDeletedReasonParticipantRemoved:
		return true
	}
	return false
}

func (e PostDeletedReason) String() string {
	return string(e)
}

func (e *PostDeletedReason) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostDeletedReason(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostDeletedReason", str)
	}
	return nil
}

func (e PostDeletedReason) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

type PostType string

const (
	PostTypeStandard        PostType = "STANDARD"
	PostTypeImportedContent PostType = "IMPORTED_CONTENT"
	PostTypeAlert           PostType = "ALERT"
	PostTypeConcierge       PostType = "CONCIERGE"
)

var AllPostType = []PostType{
	PostTypeStandard,
	PostTypeImportedContent,
	PostTypeAlert,
	PostTypeConcierge,
}

func (e PostType) IsValid() bool {
	switch e {
	case PostTypeStandard, PostTypeImportedContent, PostTypeAlert, PostTypeConcierge:
		return true
	}
	return false
}

func (e PostType) String() string {
	return string(e)
}

func (e *PostType) UnmarshalGQL(v interface{}) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PostType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PostType", str)
	}
	return nil
}

func (e PostType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}
